version: '3'

services:
  prepare_dataset:
    image: sisinflabpoliba/ducho
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=.
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    command: bash -c "nvidia-smi && demos/demo_recsys/download_amazon.sh && python3 demos/demo_recsys/prepare_dataset.py"
    volumes:
      - ./local:/Ducho/local
  extract_features:
    image: sisinflabpoliba/ducho
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=.
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    command: bash -c "nvidia-smi && python3 demos/demo_recsys/run.py"
    volumes:
      - ./local:/Ducho/local
