version: '3'

services:
  demo1:
    image: sisinflabpoliba/ducho
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=.
      - CUDA_LAUNCH_BLOCKING=1
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    command: bash -c "nvidia-smi && python3.8 demos/demo1.py"
    volumes:
      - ./data:/Ducho/data
