version: '3'

services:
  demo1:
    image: sisinflabpoliba/ducho
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - PYTHONPATH=.
    command: python3.8 demos/demo1.py
    volumes:
      - ./data:/Ducho/data
