dataset_path: ./local/data/demo1
gpu list: 0

visual:
    items:
        input_path: images
        output_path: visual_embeddings
        model: [
            { name: VGG19,  output_layers: classifier.3, reshape: [224, 224], framework: torch},
            { name: Xception, output_layers: avg_pool, reshape: [299, 299], framework: tensorflow},
        ]

textual:
    items:
        input_path: descriptions.tsv
        output_path: textual_embeddings
        model: [
              { name: sentence-transformers/all-mpnet-base-v2,  output_layers: 1, clear_text: True, framework: sentence_transformers}
          ]