dataset_path: ./local/data/demo2
gpu list: 0

audio:
      items:
            input_path: songs
            output_path: audio_embeddings
            model: [
                      { name: 'HDEMUCS_HIGH_MUSDB',  output_layers: 1, backend: 'torch' }
            ]

textual:
    items:
        input_path: genres.tsv
        output_path: textual_embeddings
        model: [
              { name: sentence-transformers/all-MiniLM-L12-v2,  output_layers: 1, clear_text: True, backend: sentence_transformers}
          ]